### PR TITLE
Fix: Fix URL regex to allow '@' in the path

### LINKED ISSUE #1050: Bug: No Bare URLs fails if url contains '@' (at)
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

URLs with an '@' symbol in the path are not enclosed completely

## How to Reproduce

1. Enable `No Bare URLs` in plugin settings
2. Disable `No Bare URIs` in plugin settings
3. Create a new note
4. Insert `https://domain.org/@user/long-kebab-case-path`
5. Execute command `Lint the current file`
6. The link is not fully enclosed

Or

Example to reproduce issue with

``` markdown
https://domain.org/@user/long-kebab-case-path
```

## Expected Behavior

The full link should be enclosed by angle brackets `<link>`.

Expected output if applicable:

``` markdown
<https://domain.org/@user/long-kebab-case-path>
```

## Actual Behavior

Only a part is enclosed with angle brackets.

Actual output if applicable:

``` markdown
<https://domain.org/>@user/long-kebab-case-path
```

## Screenshots

\-

## Device

- [x] Desktop
- [x] Mobile

## Additional Context

I will provide a PR asap.

### PR DESCRIPTION
**Pull request by marcelhas**
Closes #1050.

### CODE REVIEW

File: src/utils/regex.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ export const tableRow = /[^\n]*?\|[^\n]*?(\n|$)/m;
...
...d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|:[a-fA-F\d]{1,4}|:)|(?:[a-fA-F\d]{1,4}:){5}(?::(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|(?::[a-fA-F\d]{1,4}){1,2}|:)|(?:[a-fA-F\d]{1,4}:){4}(?:(?::[a-fA-F\d]{1,4}){0,1}:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|(?::[a-fA-F\d]{1,4}){1,3}|:)|(?:[a-fA-F\d]{1,4}:){3}(?:(?::[a-fA-F\d]{1,4}){0,2}:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|(?::[a-fA-F\d]{1,4}){1,4}|:)|(?:[a-fA-F\d]{1,4}:){2}(?:(?::[a-fA-F\d]{1,4}){0,3}:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|(?::[a-fA-F\d]{1,4}){1,5}|:)|(?:[a-fA-F\d]{1,4}:){1}(?:(?::[a-fA-F\d]{1,4}){0,4}:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|(?::[a-fA-F\d]{1,4}){1,6}|:)|(?::(?:(?::[a-fA-F\d]{1,4}){0,5}:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}|(?::[a-fA-F\d]{1,4}){1,7}|:)))(?:%[0-9a-zA-Z]{1,})?|(?:(?:[a-z0-9][-_]*)*[a-z0-9]+)(?:\.(?:[a-z0-9]-*)*[a-z0-9]+)*(?:\.(?:[a-z]{2,})))(?::\d{2,5})?(?:(?:[/?#][a-z0-9-_%/&=?$.+!*‘(,#@]*[a-z0-9-%_/$+!*‘(,])|[/])?/gi;
```
Comment (marcelhas) [inline src/utils/regex.ts:29]: The change is a single '@' at column 1430.

**Comment by pjkaufman** [comment]
Thanks for the PR. I will take a look at this tomorrow.

**Review by pjkaufman — APPROVED** [review]
Looks good to me.
